### ISSUE TITLE
dcgm-exporter POD CrashLoopBackOff or Error

### ISSUE THREAD

**Issue by Leteong** [NVIDIA/gpu-monitoring-tools#105]
msg="Failed to Listen and Server HTTP server with err: `listen tcp: address 9400: missing port in address`"

k8s version  v1.18.3
nvidia-driver version  450.51.06
NVIDIA-CARD  Tesla V100-PCIE

**Comment by atulyadavtech** [comment]
Hi ,

Please provide the environment details.
OS Version.
Deepops Version.

Thank You
Atul Yadav
