### ISSUE TITLE
Consider adding a 'nodename' label

### ISSUE THREAD

**Issue by mjpieters** [NVIDIA/gpu-monitoring-tools#110]
We monitor GPUs on multiple machines. It's easy enough to add the nodename (host name) to each exporter using Prometheus relabel configuration, but it'd be helpful if the exporter did this out of the box.

The added advantage is that the dashboard then also can use the node name as a variable and let you filter on a combination of node and GPU ID.

**Comment by mjpieters** [comment]
Actually, we just need to use 'instance', closing, will update the dashboard.

**Comment by kenwoodjw** [comment]
> Actually, we just need to use 'instance', closing, will update the dashboard.

some where get the new dashboard ,pls
