### ISSUE TITLE
 How the memory and GPU utilization defined

### ISSUE THREAD

**Issue by alienflash01** [NVIDIA/gpu-monitoring-tools#12]
In the dmon example, memory utilization and GPU utilization are calculated. For example, in the following example, memory utilization is 1%, but how is this value defined? Is it the percentage of bandwidth used during the last second ? And is there any reference document?
```
$ go build && ./dmon

# sample output

Started host engine version 1.4.3 using socket path: /tmp/dcgmrxvqro.socket
# gpu   pwr  temp    sm   mem   enc   dec  mclk  pclk
# Idx     W     C     %     %     %     %   MHz   MHz
    0    43    48     0     1     0     0  3505   936
    0    43    48     0     1     0     0  3505   936
```

**Comment by flx42** [comment]
@alienflash01 sorry, had a busy week. Were you able to find the right definition?
Using `nvidia-smi --help-query-gpu` often helps in finding the definitions you want:
```
"utilization.gpu"                                                                                         
Percent of time over the past sample period during which one or more kernels was executing on the GPU.    
The sample period may be between 1 second and 1/6 second depending on the product.                        
                                                                                                          
"utilization.memory"                                                                                      
Percent of time over the past sample period during which global (device) memory was being read or written.
The sample period may be between 1 second and 1/6 second depending on the product.                        
```

**Comment by alienflash01** [comment]
@flx42 thank you very much. I just found the explanation from here "[nvidia-smi Volatile GPU-Utilization explanation?](https://stackoverflow.com/questions/40937894/nvidia-smi-volatile-gpu-utilization-explanation)". The `nvidia-smi --help-query-gpu` command you introduced is really useful, thank you .

**Comment by chenwenyan** [comment]
Hi, what is the meaning of sm utilization of NVIDIA? Is it meaning that the percent of sm is occupied by a running job?
Could you plz explain it
