### ISSUE TITLE
Pods with dcgm-exporter fail to start

### ISSUE THREAD

**Issue by timClicks** [NVIDIA/gpu-monitoring-tools#120]
I have installed the `dcgm-exporter` helm chart, but the pods quickly enter a crash loop. 

```console
$ kubectl get pods
NAME                                           READY   STATUS             RESTARTS   AGE
dcgm-exporter-8k4s5                            0/1     CrashLoopBackOff   27         117m
dcgm-exporter-fwcxb                            0/1     CrashLoopBackOff   27         117m
dcgm-exporter-tksj6                            0/1     CrashLoopBackOff   27         117m
```

```console
$ kubectl logs pod/dcgm-exporter-8k4s5
time="2020-10-27T20:31:42Z" level=info msg="Starting dcgm-exporter"
time="2020-10-27T20:31:42Z" level=info msg="DCGM successfully initialized!"
time="2020-10-27T20:31:42Z" level=fatal msg="Error watching fields: This request is serviced by a module of DCGM that is not currently loaded"
```

Are there pre-requsites that need to be installed on the nodes?

**Comment by timClicks** [comment]
The nvidia container runtime is available on the nodes, and the k8s-device-plugin is also running happily.

```console
$ sudo docker system info
Client:
 Debug Mode: false

Server:
...
 Server Version: 19.03.6-ce
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc neuron nvidia
 Default Runtime: nvidia
 Init Binary: docker-init
 containerd version: ff48f57fc83a8c44cf4ad5d672424a98ba37ded6
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.14.198-152.320.amzn2.x86_64
 Operating System: Amazon Linux 2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 59.96GiB
...
```

**Comment by timClicks** [comment]
Running the exporter manually seems to work...

```console
$ sudo docker run -i --gpus all --rm -p 9400:9400 nvidia/dcgm-exporter:latest
Unable to find image 'nvidia/dcgm-exporter:latest' locally
latest: Pulling from nvidia/dcgm-exporter
a1125296b23d: Pull complete 
3c742a4a0f38: Pull complete 
4c5ea3b32996: Pull complete 
1b4be91ead68: Pull complete 
e93a0823362a: Pull complete 
a7548f29ba00: Pull complete 
a4a3c4393c19: Pull complete 
f6d9edaa5238: Pull complete 
Digest: sha256:69403133a54b9600337cb052cc2aafd38192f3a644a79542e4fa92a487cd3ccf
Status: Downloaded newer image for nvidia/dcgm-exporter:latest
time="2020-10-27T21:49:28Z" level=info msg="Starting dcgm-exporter"
time="2020-10-27T21:49:28Z" level=info msg="DCGM successfully initialized!"
time="2020-10-27T21:49:28Z" level=info msg="Pipeline starting"
time="2020-10-27T21:49:28Z" level=info msg="Starting webserver"
```

**Comment by timClicks** [comment]
I have been able to get the exporter running by changing the args sent to the binary from the Helm chart. Here is the snippet from `values.yaml`

```yaml
image:
  repository: nvidia/dcgm-exporter
  pullPolicy: IfNotPresent
  # Image tag defaults to AppVersion, but you can use the tag key
  # for the image tag, e.g:
  # 2.0.13-2.1.0-ubuntu18.04
  tag: latest

# Comment the following line to stop profiling metrics from DCGM
#arguments: ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
arguments: ["-k"]

```

**Comment by sturfee-petrl** [comment]
@timClicks Thank you so much😃! Your fix works. 

anyway **can you reopen** this issue to ensure we fix it. I would prefer I've never faced it)

I got this issue on AWS EKS 1.18
I used [this nvidia tutorial](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#setting-up-dcgm).

**Comment by westfly** [comment]
> I have been able to get the exporter running by changing the args sent to the binary from the Helm chart. Here is the snippet from `values.yaml`
> 
> ```yaml
> image:
>   repository: nvidia/dcgm-exporter
>   pullPolicy: IfNotPresent
>   # Image tag defaults to AppVersion, but you can use the tag key
>   # for the image tag, e.g:
>   # 2.0.13-2.1.0-ubuntu18.04
>   tag: latest
> 
> # Comment the following line to stop profiling metrics from DCGM
> #arguments: ["-f", "/etc/dcgm-exporter/dcp-metrics-included.csv"]
> arguments: ["-k"]
> ```

![image](https://user-images.githubusercontent.com/1453169/109969634-1a1d6100-7d2f-11eb-9ef4-ec688d3dec3b.png)
still not start

**Comment by pavuluri** [comment]
@westfly Have you been able to resolve this issue?   I still get readiness and liveness probes fail errors.  I tried the above workaround, but no luck.

**Comment by westfly** [comment]
> @westfly Have you been able to resolve this issue? I still get readiness and liveness probes fail errors. I tried the above workaround, but no luck.

no，I use [dcgm-exporter.yaml](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/dcgm-exporter.yaml) instead of installing with helm

**Comment by ndtreviv** [comment]
I get a similar issue with the helm chart.
The logs are worse, though, as they specify no error:
My logs:
```
time="2021-03-17T15:59:23Z" level=info msg="Starting dcgm-exporter"
time="2021-03-17T15:59:23Z" level=info msg="DCGM successfully initialized!"
time="2021-03-17T15:59:23Z" level=info msg="Collecting DCP Metrics"
time="2021-03-17T15:59:23Z" level=info msg="Kubernetes metrics collection enabled!"
time="2021-03-17T15:59:23Z" level=info msg="Pipeline starting"
time="2021-03-17T15:59:23Z" level=info msg="Starting webserver"
```

The nvidia-device-plugin was installed successfully. 

Details:
<img width="503" alt="Screenshot 2021-03-17 at 15 59 55" src="https://user-images.githubusercontent.com/1530653/111498601-fd732700-8739-11eb-9781-be8cc6a034fb.png">
<img width="1165" alt="Screenshot 2021-03-17 at 16 00 16" src="https://user-images.githubusercontent.com/1530653/111498617-0106ae00-873a-11eb-9628-b46d575eb07c.png">

**Comment by westfly** [comment]
> I get a similar issue with the helm chart.
> The logs are worse, though, as they specify no error:
> My logs:
> 
> ```
> time="2021-03-17T15:59:23Z" level=info msg="Starting dcgm-exporter"
> time="2021-03-17T15:59:23Z" level=info msg="DCGM successfully initialized!"
> time="2021-03-17T15:59:23Z" level=info msg="Collecting DCP Metrics"
> time="2021-03-17T15:59:23Z" level=info msg="Kubernetes metrics collection enabled!"
> time="2021-03-17T15:59:23Z" level=info msg="Pipeline starting"
> time="2021-03-17T15:59:23Z" level=info msg="Starting webserver"
> ```
> 
> The nvidia-device-plugin was installed successfully.
> 
> Details:
> <img alt="Screenshot 2021-03-17 at 15 59 55" width="503" src="https://user-images.githubusercontent.com/1530653/111498601-fd732700-8739-11eb-9781-be8cc6a034fb.png">
> 
> **Note**: This was not the default image or set of arguments - after it failed the first few times I changed the helm values to match @timClicks values.
> 
> <img alt="Screenshot 2021-03-17 at 16 00 16" width="1165" src="https://user-images.githubusercontent.com/1530653/111498617-0106ae00-873a-11eb-9628-b46d575eb07c.png">

try to make initialDelaySeconds bigger
```YAML
livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.service.port }}
          initialDelaySeconds: 20

```

**Comment by ndtreviv** [comment]
> try to make initialDelaySeconds bigger
> 
> ```yaml
> livenessProbe:
>           httpGet:
>             path: /health
>             port: {{ .Values.service.port }}
>           initialDelaySeconds: 20
>           periodSeconds: 5
>         readinessProbe:
>           httpGet:
>             path: /health
>             port: {{ .Values.service.port }}
>           initialDelaySeconds: 20
> ```

How do I do this in the helm chart values file?

**Comment by davbera** [comment]
I had same issue as @ndtreviv and I solved it by manually updating initialDelaySeconds, as stated by @westfly, on the DaemonSet 
It would be nice if the value of initialDelaySeconds can be specified in the helm chart values file.

**Comment by jiangxiaosheng** [comment]
I had this same issue and I manually deploy the daemonset as @westfly did. However, prometheus does not collect the metrics from the DCGM exporter. Any suggestions? Thanks sincerely in advance.
