### ISSUE TITLE
is there a dashboard json file for grafana?

### ISSUE THREAD

**Issue by lexuszhi1990** [NVIDIA/gpu-monitoring-tools#13]
thx

**Comment by guptaNswati** [comment]
For k8s, we have a custom cluster monitoring stack built on kube-prometheus, including modified node-exporter and Grafana and is shipped as part of [KONG](https://docs.nvidia.com/datacenter/kubernetes-install-guide/index.html#kubernetes-setup-monitoring]), but no separate json for now.

**Comment by lexuszhi1990** [comment]
ok, thanks very much
