### ISSUE TITLE
Questions about EventType, EventData, and Xid

### ISSUE THREAD

**Issue by ruiwen-zhao** [NVIDIA/gpu-monitoring-tools#150]
Hi,

I have some questions about the relations between NVML's [event type](https://docs.nvidia.com/deploy/nvml-api/group__nvmlEventType.html#group__nvmlEventType), event data, and the Xid error codes. I am posting them here to see if someone might have the answers.

1. When we register event for a device using [RegisterEventForDevice](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/bindings/go/nvml/bindings.go#L137), what Xid errors are covered by a certain event type? Does the event type cover all Xid errors that share the bit mask? i.e. when registering`nvmlEventTypeXidCriticalError`, which is 8, we will be listening to Xid codes 8, 9, 11, 12, 13, and 24-31, etc? 

If so, then why event type nvmlEventTypeDoubleBitEccError (0x0000000000000002LL) does not cover Xid 48? And If not, if there any doc showing what Xid errors are covered by each event type? 

2. When we get an event from [WaitForEvents](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/bindings/go/nvml/bindings.go#L174), is the eventData the Xid code for the error? Will the eventData always be present, no matter which eventType it belongs to? I am asking because the [API doc](https://docs.nvidia.com/deploy/nvml-api/structnvmlEventData__t.html#structnvmlEventData__t) says eventData "Stores XID error for the device in the event of nvmlEventTypeXidCriticalError,."

**Comment by guptaNswati** [comment]
You can find more information about XID errors from here https://docs.nvidia.com/deploy/xid-errors/index.html#topic_4. 
You can register for multiple events for a given device using the `|` operator 
Yes, the event data is the xid code for that event https://docs.nvidia.com/deploy/nvml-api/structnvmlEventData__t.html#structnvmlEventData__t

**Comment by ruiwen-zhao** [comment]
Thanks @guptaNswati! I guess my question is more of, if I call registerEventForDevice with event type `nvmlEventTypeXidCriticalError`, will I get an event in case of *any* Xid errors, or just some of them? If it is just some of them, then what Xid errors are considered an XidCriticalError?

**Comment by guptaNswati** [comment]
Yes, any xid error will trigger this event.

**Comment by ruiwen-zhao** [comment]
@guptaNswati Thanks for the clarification!
