### ISSUE TITLE
Helm chart pointing to 2.3.1 container, which is not available on nvcr.io

### ISSUE THREAD

**Issue by francoishernandez** [NVIDIA/gpu-monitoring-tools#164]
Hi there,
While trying to setup GPU monitoring on our kubernetes cluster, I faced the following `ErrImagePull`
```
Failed to pull image "nvcr.io/nvidia/k8s/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04": rpc error: code = Unknown desc = Error response from daemon: manifest for nvcr.io/nvidia/k8s/dcgm-exporter:2.1.4-2.3.1-ubuntu18.04 not found: manifest unknown: manifest unknown
```
After **checking my NGC key was working**, I checked the catalog, and it seems the 2.3.1 containers are missing:
https://ngc.nvidia.com/catalog/containers/nvidia:k8s:dcgm-exporter/tags
![Screenshot from 2021-03-10 15-35-20](https://user-images.githubusercontent.com/14880403/110645460-4402d780-81b6-11eb-9e15-1ec68f37af21.png)

EDIT: for those who might be new to this (as I am), you can override the value to point to another tag similarly to the [prometheus setup](https://docs.nvidia.com/datacenter/cloud-native/kubernetes/dcgme2e.html#setting-up-prometheus).

**Comment by elezar** [comment]
Hi @francoishernandez. Thanks for reporting this. Is this a duplicate of #161 (or at least an issue with the same root cause)?

**Comment by elezar** [comment]
Hi @francoishernandez. We have pushed the images to `nvcr.io`. Please check if the issue is resolved.

**Comment by francoishernandez** [comment]
Looks like it, thanks!
