### ISSUE TITLE
"/usr/local/bin/dcgm-exporter: line 55: nvidia-smi: command not found" in DCGM exporter

### ISSUE THREAD

**Issue by kunmingg** [NVIDIA/gpu-monitoring-tools#2]
After deploy on kubernetes following [instructions](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/README.md#deploy-on-kubernetes-cluster).

Thanks

**Comment by guptaNswati** [comment]
Do you have [nvidia-docker](https://github.com/NVIDIA/nvidia-docker#quickstart) installed?

**Comment by flx42** [comment]
@kunmingg I've fixed the FAQ, thank you for pointing that out. `alpha` was referring to the status of device plugins in general, not to the status of our implementation.

**Comment by flx42** [comment]
Maybe I closed a little bit too quick, let us know if that doesn't work out for you.

**Comment by kunmingg** [comment]
@flx42 I have nvidia-gpu-device-plugin installed in cluster.
Do I need more config on pod side to use nvidia-smi?

**Comment by guptaNswati** [comment]
Running dcgm-exporter is independent of the device-plugin, you just need to set the default runtime to nvidia.
