### ISSUE TITLE
GPU Utilization metric (DCGM_FI_DEV_GPU_UTIL) disabled by default

### ISSUE THREAD

**Issue by Minkyu-Choi** [NVIDIA/gpu-monitoring-tools#200]
Currently, GPU Utilization metric(DCGM_FI_DEV_GPU_UTIL) is commented out in etc/dcgm-exporter/default-counters.csv file.

Is there any special reason for commenting out this metric? I'm not sure if this is intended or not.
If it is not, I would like to submit PR fixing this.

Thanks,
Mike

**Comment by YH-Wu** [comment]
You may check #143

**Comment by Minkyu-Choi** [comment]
> You may check #143

Thanks, perfect.
