### ISSUE TITLE
Have trouble in making docker image of pod-gpu-metrics-exporter

### ISSUE THREAD

**Issue by JunFugithub** [NVIDIA/gpu-monitoring-tools#23]
Hi there, I'd like to do some diy on __pod-gpu-metrics-exporter__ image, so I tried to rebuild the dockfile under the path of _gpu-monitoring-tools/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter/_. However it stuck with the 4th step of dockerfile `RUN go install -v pod-gpu-metrics-exporter` with this error occurred 
```bash
# pod-gpu-metrics-exporter
./server.go:17:2: podResourcesMaxSize redeclared in this block
	previous declaration at ./kubelet_server.go:17:38
./server.go:20:6: connectToServer redeclared in this block
	previous declaration at ./kubelet_server.go:20:56
./server.go:26:19: connectToServer.func1 redeclared in this block
	previous declaration at ./kubelet_server.go:26:19
./server.go:36:6: getListOfPods redeclared in this block
	previous declaration at ./kubelet_server.go:36:79
The command '/bin/sh -c go install -v pod-gpu-metrics-exporter' returned a non-zero code: 2
```
could you please take a look at it if available? huge THANKS in advance

**Comment by guptaNswati** [comment]
Oh server.go was renamed to kubelet_server.go and but looks it dint get pushed properly. I have fixed it, you should be able to build now.
