### ISSUE TITLE
nvlink bandwidth metrics

### ISSUE THREAD

**Issue by hholst80** [NVIDIA/gpu-monitoring-tools#24]
For visibility and tracking.

In [exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter) we can see that the `nvlink_bandwidth_total` counter is disabled. Can anyone give an explanation to why and and what is blocking from enabling this counter?

**Comment by guptaNswati** [comment]
This metric was buggy, should be fixed in DCGM 1.6.0
