### ISSUE TITLE
nvidia-smi not found

### ISSUE THREAD

**Issue by papagalu** [NVIDIA/gpu-monitoring-tools#27]
Image nvidia/dcgm-exporter:1.4.6 does not have nvidia-smi installed in it.

Dockerfile starts from a ubuntu 16.04 base image, and does not install nvidia-utils.

I ran a nvidia/cuda container, installed the utils and successfully ran nvidia-smi.

could you please update the Dockerfile or make a guide on how to build the image?

**Comment by guptaNswati** [comment]
Yes the driver utilities are not installed inside the DCGM container, but nvidia runtime takes care of it. Did you run the container with `--runtime=nvidia`?  You do not need to install driver utils inside CUDA or DCGM container if you have driver installed on the host machine where the runtime will take care of injecting the right libs inside the container. 

For building the DCGM container, you need to download and copy the deb in the dcgm-exporter directory and do `docker build -t "dcgm-exporter" .`

**Comment by guptaNswati** [comment]
Hopefully, this is resolved. If not, you can open again.

**Comment by to266** [comment]
Hi, I'm having this issue when running `nvidia/dcgm-exporter:1.0.0-beta` on GKE as a pod in daemonset. 
I'm sure that the `nvidia-gpu-device-plugin` is installed and functioning since I'm running other things on it successfully, but it's unclear how to correctly set the runtime, if it's needed at all

**Comment by RenaudWasTaken** [comment]
Hello @to266 !

GKE unfortunately doesn't use the NVIDIA Container Toolkit to run GPU containers. This leads to incompatibilities and inconsistencies on their platform.

Unfortunately this means that metrics support in GKE isn't really supported outside stack driver. You probably should open a ticket with them to see if they can address your issue :)

**Comment by delulu** [comment]
> Yes the driver utilities are not installed inside the DCGM container, but nvidia runtime takes care of it. Did you run the container with `--runtime=nvidia`? You do not need to install driver utils inside CUDA or DCGM container if you have driver installed on the host machine where the runtime will take care of injecting the right libs inside the container.
> 
> For building the DCGM container, you need to download and copy the deb in the dcgm-exporter directory and do `docker build -t "dcgm-exporter" .`

I met the same issue, and in my case the docker runtime has been set to nvidia. 

But it seems the /usr/local/nvidia has not been mounted into container and I have to mount it in dcgm-exporter in its k8s definition yaml file.

@guptaNswati do you have any idea about it?

**Comment by RenaudWasTaken** [comment]
`/usr/local/nvidia` doesn't get automatically mounted in your container :)
Can you open an issue against this repository with the following issue template: https://github.com/NVIDIA/nvidia-docker/blob/master/.github/ISSUE_TEMPLATE.md

Additionally can you tell us what is the result you expect and the result you are seeing?

**Comment by delulu** [comment]
@RenaudWasTaken thank you, I've opened the issue https://github.com/NVIDIA/nvidia-docker/issues/1226.

What I'm expecting is the utility capability can be mounted inside container automatically when it's set in env variable NVIDIA_DRIVER_CAPABILITIES=utility.
