### ISSUE TITLE
K8S incompatibility- Hostname in metrics

### ISSUE THREAD

**Issue by shmulikah** [NVIDIA/gpu-monitoring-tools#28]
I'm running the prometheus exporter nodes as part of my K8S cluster.
All of the dcgm metrics have an element with the name"instance" which is basically the IP address of the node (e.g instance="172.21.4.101:9100")

I'm having trouble when trying to create a rather complex promql query that "joins" elements from kube_state_metrics (e.g. kube_node_lables).
the kube_state_metrics has an instance element as well but unfortunately it holds only the K8S cluster ip and not the actual node IP. in some metrics there is a node element which is the hostname.  

Is it possible that the dcgm exporter will export the hostname/nodename element in addition to instance?

Thanks

**Comment by guptaNswati** [comment]
dcgm-exporter is supposed to be run inside or outside of k8s cluster, adding any k8s specific metrics would hamper that. But it can be done in [pod-exporter](https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter/), it basically adds k8s pod info to the metrics. Do you want to do a PR for this?

**Comment by guptaNswati** [comment]
No action, so closing for now. Reopen when you want it to be addressed.
