### ISSUE TITLE
Help pulling field #4

### ISSUE THREAD

**Issue by markyjackson-taulia** [NVIDIA/gpu-monitoring-tools#29]
I am trying to figure out how to add field #4 here: https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter#L43

and then how to call like here: https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter#L70

I am sure I am not doing something right and I apologize for what may be a super easy question

**Comment by guptaNswati** [comment]
If you are asking about nvlink metrics, they are already enabled from DCGM 1.4.6 onwards. Can you detail more about what you are trying to do?

**Comment by markyjackson-taulia** [comment]
@guptaNswati I just want to be able to call field # 4 like https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter#L44

I just need some help in how to add that

**Comment by guptaNswati** [comment]
Do you want to add this `DCGM_FI_DEV_COUNT 4`? 

You can do

`dcgmi dmon -d "${COLLECT_INTERVAL_MS}" -e "4, 54,"\`

Add device_count after https://github.com/NVIDIA/gpu-monitoring tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter#L68
`device_count = $(i++) # field 4`                                                                                                   
        
`printf "dcgm_%s{gpu=\"%s\",uuid=\"%s\",device_count=\"%s\"} %s\n", name, gpu, uuid, device_count, value > out".swp"`

**Comment by markyjackson-taulia** [comment]
Thank you so much @guptaNswati
