### ISSUE TITLE
How to get mem.total with nvml

### ISSUE THREAD

**Issue by pytimer** [NVIDIA/gpu-monitoring-tools#3]
Hi, i use `gpu-monitoring-tools` to collect my nvidia gpu metrics, i want to get memory total, like 
```
# nvidia-smi --format=csv --query-gpu=memory.total,memory.used,memory.free,name
memory.total [MiB], memory.used [MiB], memory.free [MiB], name
7840 MiB, 20 MiB, 7820 MiB, Tesla P4
```

i see `deviceGetMemoryInfo` not return mem.total in `bindings/go/nvml/bindings.go`. Should it add  this value?

In addition, i run `nvidia-smi -q`, return below information:
```
Display Mode                    : Enabled
Display Active                  : Disabled
Persistence Mode                : Enabled
Accounting Mode                 : Enabled
Accounting Mode Buffer Size     : 4000
```

how can i use this library to get these information? Thanks.

**Comment by guptaNswati** [comment]
I have added these APIs, now you can do this:
```
device, _ := nvml.NewDevice(id)

// total memory
device.Memory

// used and free
st, _ := device.Status()
st.Memory.Global.Used
st.Memory.Global.Free

// device modes
mode, _:= device.GetDeviceMode()
mode.DisplayInfo.Mode
mode.DisplayInfo.Active
mode.Persistence
mode.AccountingInfo.Mode
mode.AccountingInfo.BufferSize
```

**Comment by pytimer** [comment]
Thanks for your reply. 

I already update my project, it works well. But i have a question that why device memory return value is MB rather than bytes? If i want to collect gpu metrics to prometheus, is it better to bytes?

**Comment by guptaNswati** [comment]
There is no particular reason, except to be consistent with what nvidia-smi returns. How is converting to bytes better for Prometheus?

**Comment by pytimer** [comment]
Add some function convert value to bytes or MB, or others unit?

Like below example code:

```go
package main

import "fmt"

type memoryUnit uint64

func (u memoryUnit) Bytes() memoryUnit {
	return u
}

func (u memoryUnit) KB() memoryUnit {
	u /= 1024
	return u
}

func (u memoryUnit) MB() memoryUnit {
	u /= 1024 * 1024
	return u
}

func main() {
	total := memoryUnit(2097152)
	fmt.Printf("total: %d B\n", total.Bytes())
	fmt.Printf("total: %d KB\n", total.KB())
	fmt.Printf("total: %d MB\n", total.MB())
}
```

output:
```
total: 2097152 B
total: 2048 KB
total: 2 MB
```

I don't know is the idea reasonable?

**Comment by guptaNswati** [comment]
It is. Will look into adding this.
