### ISSUE TITLE
dcgm processInfo return "No data is available"

### ISSUE THREAD

**Issue by chenk008** [NVIDIA/gpu-monitoring-tools#32]
I find the pid  by using nvidia-smi,it show 
`+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory | 
|  GPU       PID   Type   Process name                             Usage      | 
|=============================================================================| 
|    0      5611      C   python3                                     5073MiB | 
|    0      9334      C   python                                      1805MiB | 
+-----------------------------------------------------------------------------+ 
`

Then 

> dcgmi stats -p 5611 -v

always result
> Error: Unable to get information for process with PID 5611. Return: No data is available.

**Comment by chenk008** [comment]
`dcgmi stats -p 5611 -v` can only inspect the pid in the host.
If the process is running in docker,`dcgmi stats` alawys show :No data is available.

**Comment by guptaNswati** [comment]
Are you running dcgmi stats inside dcgm-exporter container? Do you have any GPU processes running inside the same container?

**Comment by chenk008** [comment]
> Are you running dcgmi stats inside dcgm-exporter container? Do you have any GPU processes running inside the same container?

The GPU processes  are running inside other container.And  running `dcgmi stats`   inside dc gm-exporter container result  `No data is available.`

And running `dcgmi stats`  in the host also show `No data is available.`

Can dcgmi inspect process in other container?

**Comment by chenk008** [comment]
> > Are you running dcgmi stats inside dcgm-exporter container? Do you have any GPU processes running inside the same container?
> 
> The GPU processes are running inside other container.And running `dcgmi stats` inside dc gm-exporter container result `No data is available.`
> 
> And running `dcgmi stats` in the host(not inside container) also show `No data is available.`
> 
> Can dcgmi inspect process in other container?

I test on some other machine , running `dcgmi stats --pid $pid -v` in the host(not inside container) ,some process will show the result, some process still `No data is available.`

**Comment by CermakM** [comment]
This is intriguing... I am probably facing the same issue. Is there any solution to actually get data about processes running in other containers?

**Comment by chenk008** [comment]
> This is intriguing... I am probably facing the same issue. Is there any solution to actually get data about processes running in other containers?

When use dcgm to inspect process, the target process start time must be after dcgm's start time
