### ISSUE TITLE
Several bugs for node-exporter/pod-gpu-node-exporter-daemonset.yaml

### ISSUE THREAD

**Issue by Cherishty** [NVIDIA/gpu-monitoring-tools#33]
I'd like to collect node/pod metrics for GPU, and when applying [pod-gpu-node-exporter-daemonset.yaml](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/k8s/node-exporter/pod-gpu-node-exporter-daemonset.yaml), I find several bugs and suggestion

1.  the output of `nvidia-dcgm-exporter` can **NOT** be integrated into` node-exporter`, the root cause is: the metrics of `nvidia-dcgm-exporter` is redirect to **/run/prometheus/dcgm.prom**, but in node-exporter it is set to collect from **/run/dcgm** , so of course you can get NOTHING

2. pod exporter does NOT work and throw an error says 

> failed to get devices Pod information: failure connecting to /var/lib/kubelet/pod-resources/kubelet.sock: context deadline exceeded

I check the /var/lib/kubelet/pod-resources under my node but it's an empty folder. I am using k8s 1.14 where **kubelet.sock** is located under `/var/lib/kubelet/device-plugins`.
Then following [this issue](https://github.com/NVIDIA/gpu-monitoring-tools/issues/20), I modify the hostpath to the folder of   **kubelet.sock**, while the pod-exporter raise a new exception:

> failed to get devices Pod information: failure getting pod resources rpc error: code = Unimplemented desc = unknown service v1alpha1.PodResourcesLister

I assume this is due to incompatible k8s protobuf, so may you provide the corresponding docker image?

3. From the guide, I assume the key of GPU metrics between **node-exporter** and **pod-exporter** is totally seem, such as `dcgm_gpu_utilization`, which is not a good pratice as I can not simply distinguish them. You should give them different key, like `dcgm_gpu_utilization` for node level, and `pod_gpu_utilization` for pod level

**Comment by Cherishty** [comment]
Moreover, not sure if pod exporter can expose the metrics of GPU limits and requests, which is provided when user submit a pod?

**Comment by guptaNswati** [comment]
Do you have all the pre-reqs completed https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter#prerequisites Seems like you have not set the **KUBELET_EXTRA_ARGS=--feature-gates=KubeletPodResources=true**. For pod resources there should be a separate socket under /var/lib/kubelet/pod-resources when you set enable the PodResources feature gate

**Comment by kuromt** [comment]
I gave same problem with k8s v1.16 which set KubeletPodResources true in default.

In a gpu server,  I try to run `curl localhost:9400/gpu/metrics` , but it returns connection refused.

I assume that exporter fails to bind 9400 port in the server with silence.

**Comment by damon008** [comment]
In a gpu server, I try to run curl localhost:9400/gpu/metrics , but it returns 
```
E1204 04:49:12.763582       1 http.go:48] error responding to 10.244.0.225:9400/gpu/metrics: open /run/dcgm/dcgm-pod.prom: no such file or directory
```

**Comment by guptaNswati** [comment]
@kuromt this endpoint is available only inside the container unless you do port-forwarding. You are combining docker run instructions with k8s. If you want to see the metrics on the host, you will need to do 
$ kubectl port-forward "dcgm-pod-name" 9400

**Comment by guptaNswati** [comment]
@damon008 this means you have error running the exporter. Please make sure you follow the pre-reqs and run exported on a supported GPU.
