### ISSUE TITLE
Memory.ECCErrors is null in nvml binding

### ISSUE THREAD

**Issue by Ehekatl** [NVIDIA/gpu-monitoring-tools#35]
On Tesla T4, with ECC mode enabled, the nvml binding does not report ecc error count correctly.
I got nil value with error NVML_ERROR_NOT_SUPPORTED, however nvidia-smi command line tool works without problem

**Comment by guptaNswati** [comment]
Can post the output of nvidia-smi? And what is your nvml.h version?
