### ISSUE TITLE
what is the meaning of "dcgm_pcie_rx_throughput"?

### ISSUE THREAD

**Issue by zzpp3377** [NVIDIA/gpu-monitoring-tools#37]
I have seen the help message "# HELP dcgm_pcie_rx_throughput Total number of bytes received through PCIe RX (in KB)". I think that it means the dcgm_pcie_rx_throughput is the sum of bytes received since the GPU up. But , i found that the value of dcgm_pcie_rx_throughput is not monotonous growth. So, what's the real meaning of dcgm_pcie_rx_throughput?
     I need some help.

**Comment by RenaudWasTaken** [comment]
Hello!

With the new version we use the same counters as DCGM, check the documentation here: https://docs.nvidia.com/datacenter/dcgm/1.7/dcgm-api/group__dcgmFieldIdentifiers.html#group__dcgmFieldIdentifiers
