### ISSUE TITLE
Improve the bare-metal install experience of prometheus-dcgm 

### ISSUE THREAD

**Issue by kriszentner** [NVIDIA/gpu-monitoring-tools#39]
After trying to get the bare-metal install of prometheus-dcgm working, I have a little feedback:

## README Prerequisites

One of the prerequisites listed on the [prometheus-dcgm README](https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm) should be NVIDIA datacenter-gpu-manager. If you end up just at the prometheus-dcgm page instead of going to the root gpu-monitoring-tools page, it's easy to miss. It would also be nice to expose the repository containing the datacenter-gpu-manager instead of forcing the user to go through the loginwall to download it. This makes automation much more practical.

Another prerequisite that should be mentioned is node_exporter (and the configuration of). Though it's obvious when looking at the [docker-compose.yml](https://github.com/NVIDIA/gpu-monitoring-tools/blob/5180ae2321a86df14499c3cd93f02562f29139ad/exporters/prometheus-dcgm/docker/docker-compose.yml) this information should be front and center in the README so one knows that this isn't a standalone monitoring daemon, but requires node_exporter to expose it's information to the prometheus daemon.

## dcgm-exporter bash script
Related, the [dcgm-exporter](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter/dcgm-exporter) script presumes the user has installed the correct prerequisites. It would be nice if there was something like a simple:

```bash
if [ -x /usr/bin/dcgmi ];then
  >&2 echo "ERROR: You're missing the dcgmi binary. Install the datacenter-gpu-manager package"
  exit 1
fi
if [ -x /usr/bin/nv-hostengine];then
  >&2 echo "ERROR: You're missing the nv-hostengine binary. Install the datacenter-gpu-manager package"
  exit 1
fi
```

## prometheus-dcgm.service file

The [prometheus-dcgm.service](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/bare-metal/prometheus-dcgm.service) file should have the `-e` arguement like the docker container has, otherwise the service just restarts all day long without nv-hostengine to get the shell script to daemonize. Like so
  ```service
  ExecStart=/usr/local/bin/dcgm-exporter -e
  ```

**Comment by RenaudWasTaken** [comment]
Hello!

I've spent some time improving the user experience, hope this helps!
