### ISSUE TITLE
Error parsing dcgm.prom

### ISSUE THREAD

**Issue by Gmax76** [NVIDIA/gpu-monitoring-tools#4]
Hi, 
I have an issue using the collector on a dgx server. 
These two metrics are empty for every gpu(no value inserted at the end of line in the .prom file):
dcgm_nvlink_replay_error_count_total
dcgm_nvlink_recovery_error_count_total

Some info on the system:
GPU: Tesla V100-SXM2-16GB
Driver Version: 384.125

On another server with the same package but different hardware (Tesla P100-SXM2-16GB) The metrics are all fine.

**Comment by guptaNswati** [comment]
If you are using the dcgm-exporter script directly, comment out fields 156,200,201 for now. There is a bug in DCGM 1.4.3 causing this.

**Comment by Gmax76** [comment]
The metrics impacted here are not 156 200 201 but 429 and 439

**Comment by guptaNswati** [comment]
Removing nvlink metrics is not necessary. There is an overflow in printing the values of fields 156,200,201 which was causing the script to leave any last two records empty. For instance:

`dcgmi dmon -e 156,200`

`0           N/A161262243332996445`
