### ISSUE TITLE
node-exporter OOMKilled

### ISSUE THREAD

**Issue by deng1028** [NVIDIA/gpu-monitoring-tools#41]
My node-exporter daemonset was running fine for approx. 12 hours before terminated due to OOMKilled. It was using nvidia/dcgm-exporter:1.4.6 and I tried different version of node-exporter images, e.g. quay.io/prometheus/node-exporter:v0.16.0, v0.17.0 and v0.18.1. and disabled unnecessary collectors (e.g. wifi) but still have the same issue.

I noticed that on Kibana GPU metric (dcgm_gpu_temp shown below) somehow keeps growing:
<img width="1385" alt="metrics" src="https://user-images.githubusercontent.com/5489750/64276851-c2b1f100-cefd-11e9-83ee-b6c5db5ff5dd.png">

Any idea what's going on and how to debug? Thanks.

**Comment by deng1028** [comment]
I noticed that this happens only when I include `prometheus.io/scrape: "true"` in the daemonset configs so that metricbeat can scrape the metrics via autodiscover. Any idea? Thanks.

**Comment by RenaudWasTaken** [comment]
Hello!

Let me know if you still see this memory leak with V2. This is pretty concerning :)
Thanks for your feedback :)
