### ISSUE TITLE
Exporter output appears out of order

### ISSUE THREAD

**Issue by thim22** [NVIDIA/gpu-monitoring-tools#42]
Metrics for gpu0 appear underneath their respective "# TYPE" line as expected but all other gpu's metrics are grouped together at the bottom under "# TYPE dcgm_fb_used gauge"

See output:
https://gist.github.com/thim22/7e81f30796cfad2012262f8abb0929f4

**Comment by RenaudWasTaken** [comment]
TYPE and HELP should only appear once in the file :)
