### ISSUE TITLE
Change dcgm-exporter to expose metrics through prometheus web server

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/gpu-monitoring-tools#43]
dcgm-exporter use shell scripts to wrote metrics to a static file ('/run/prometheus/dcgm.prom') which expose statistics on local disk. Node-exporter read this file via `--collector.textfile.directory`. 

The disadvantage of this pattern is dcgm has dependency on node exporter to collect GPU metrics. A lots of users may already has node exporter setup for their non accelerator workloads. I would suggest to host a prom server and using dcgm bindings to get metrics separately. 

I can help on the work

**Comment by Jeffwan** [comment]
Another concern is `pod-nvidia-gpu-metrics-exporter` uses `/run/prometheus/dcgm.prom` and insert container/pod/pod_namespace dimensions. Metrics name are exact same. I am not sure if this is a good pattern. Once we change to web based metrics, `pod-nvidia-gpu-metrics-exporter` need to be updated as well.

**Comment by RenaudWasTaken** [comment]
Hello!

Exposing metrics through an HTTP server is the current pattern of V2.
Hope this helps!
