### ISSUE TITLE
GPU metrics node exporter doesn't work in EKS 

### ISSUE THREAD

**Issue by chengnignzhang** [NVIDIA/gpu-monitoring-tools#44]
Hey,
       I installed the daemon set in my EKS cluster for GPU node only, and I already labelled my GPU node as described in the instructions.  
    yaml file: gpu-node-exporter-daemonset.yaml
      However I found there is 0 pod which is running for this daemonset. 
     The gpu node is using ami with below prerequisites:
       NVIDIA drivers
       The nvidia-docker2 package
       The nvidia-container-runtime (as the default runtime)
https://docs.aws.amazon.com/eks/latest/userguide/gpu-ami.html

I installed the NVIDIA device plugin for Kubernetes with below commands:
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml

Could you please help look into this?

Thanks.
Chengning

**Comment by chengnignzhang** [comment]
hey I also attached my gpu driver version here.

| NVIDIA-SMI 418.40.04    Driver Version: 418.40.04    CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M60           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   28C    P8    22W / 150W |      0MiB /  7618MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+

**Comment by guptaNswati** [comment]
Can you share whats
$kubectl get pods --all-namespaces
$kubectl get nodes --show-labels

**Comment by Jeffwan** [comment]
Hi @chengnignzhang I didn't see problems running it on EKS. Could you check the reason why no pods get scheduled?
