### ISSUE TITLE
GPU metrics Dashboard outside cluster access

### ISSUE THREAD

**Issue by deepakkuk** [NVIDIA/gpu-monitoring-tools#45]
is it possible to access gpu metrics dashboard access outside cluster??

**Comment by guptaNswati** [comment]
Yes, you can do it by ingress https://kubernetes.io/docs/concepts/services-networking/ingress/

**Comment by deepakkuk** [comment]
how i can change grafana.ini for anonymous access.

**Comment by deepakkuk** [comment]
thank you ma'am
