### ISSUE TITLE
Compatibility with K8N 1.16

### ISSUE THREAD

**Issue by steffenteichmannhska** [NVIDIA/gpu-monitoring-tools#48]
I tried to install the **https://nvidia.github.io/gpu-monitoring-tools/helm-charts**
on my k8n cluster seems to be a compatibility problem with K8N 1.16
is there a solution?

**Comment by guptaNswati** [comment]
Are you having issue with helm init or deploying the operator? With v1.16, its a known issue that helm fails to initialize, see this https://github.com/helm/helm/issues/6374. 

You may need to update the API version, something like
`$  helm init --service-account tiller --override spec.selector.matchLabels.'name'='tiller',spec.selector.matchLabels.'app'='helm' --output yaml | sed 's@apiVersion: extensions/v1beta1@apiVersion: apps/v1@' | kubectl apply -f -`
