### ISSUE TITLE
Have you tested kubernetes dcgm-exporter-daemonset.yaml?

### ISSUE THREAD

**Issue by dkozlov** [NVIDIA/gpu-monitoring-tools#5]
Trying to deploy 
https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/dcgm-exporter-daemonset.yaml

daemonset "dcgm-exporter-daemonset" created
But curl: (7) Failed to connect to 10.233.109.167 port 9100: Connection refused

Could you please provide correct yaml file for Kubernetes metrics

**Comment by dkozlov** [comment]
Ok, I managed to make it work
`apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: dcgm-exporter-daemonset
spec:
  template:
    metadata:
      labels:
        name: dcgm-exporter-ds
    spec:
      containers:
      - name: dcgm-exporter
        image: nvidia/dcgm-exporter
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        volumeMounts:
        - name: collector-textfiles
          mountPath: /run/prometheus
          readOnly: false
      - name: node-exporter
        image: quay.io/prometheus/node-exporter
        args:
        - --collector.textfile.directory=/run/prometheus/
        - --web.listen-address=0.0.0.0:9100
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        ports:
        - containerPort: 9100
          hostPort: 9100
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
          requests:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
        - name: collector-textfiles
          mountPath: /run/prometheus
          readOnly: true
        - mountPath: /host/proc
          name: proc
          readOnly: true
        - mountPath: /host/sys
          name: sys
          readOnly: true
      hostNetwork: true
      hostPID: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/not-ready
        operator: Exists
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/disk-pressure
        operator: Exists
      - effect: NoSchedule
        key: node.kubernetes.io/memory-pressure
        operator: Exists
      volumes:
      - hostPath:
          path: /proc
          type: ""
        name: proc
      - hostPath:
          path: /sys
          type: ""
        name: sys
      - name: collector-textfiles
        emptyDir:
          medium: Memory
      nodeSelector:
        node-type: GPU
`

**Comment by guptaNswati** [comment]
dcgm-exporter doesn't push metrics to an endpoint, but writes to a file. Yeah this should work, you can make these metrics collect through node-exporter.

**Comment by dkozlov** [comment]
@guptaNswati Do you know how I can skip nvidia/dcgm-exporter on CPU nodes or just make it not to fail?

**Comment by dkozlov** [comment]
Create issue https://github.com/NVIDIA/gpu-monitoring-tools/issues/6
