### ISSUE TITLE
Decouple gpu-monitoring-tools with node exporter 

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/gpu-monitoring-tools#52]
Right now, gpu-monitoring-tools doesn't have a prometheus server. It relies on node exporter to read static file `/run/prometheus/dcgm.prom`. 

Most of the users probably already install node exporters. I am curious if we should decouple these two components and create prometheus server directly.

**Comment by guptaNswati** [comment]
You don't have to rely on node-exporter, we also have an example deployment where you can add a metrics endpoint directly to Prometheus https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/exporters/prometheus-dcgm/k8s/pod-gpu-metrics-exporter#deploy-on-kubernetes-cluster
