### ISSUE TITLE
Replace shell command with nvml library to populate GPU metrics

### ISSUE THREAD

**Issue by Jeffwan** [NVIDIA/gpu-monitoring-tools#53]
Currently, dcgm exporter run `dcgmi dmon` command to populate metrics. I am thinking if it's ok to move to golang and use `nvml` library to get these metrics instead. This would be easier for development and maintenance in long run.

**Comment by guptaNswati** [comment]
You can use the DCGM go bindings https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/bindings/go/samples/dcgm
