### ISSUE TITLE
ld: unknown option: --unresolved-symbols=ignore-in-object-files

### ISSUE THREAD

**Issue by sjc960115** [NVIDIA/gpu-monitoring-tools#55]
When I build project using gpu-monitoring-tools on Darwin, there raises error:
```
ld: unknown option: --unresolved-symbols=ignore-in-object-files
```
I find https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/bindings/go/nvml/bindings.go#L5.
```
--unresolved-symbols=ignore-in-object-files
```
Above not for darwin os.
I use
```
// #cgo linux LDFLAGS: -ldl -Wl,--unresolved-symbols=ignore-in-object-files
// #cgo darwin LDFLAGS: -ldl -Wl,-undefined,dynamic_lookup
```
to solve my problem, but I not sure that works for others.

**Comment by iminders** [comment]
It works for: https://github.com/tradingAI/runner/issues/20

@sjc960115 thx

**Comment by RenaudWasTaken** [comment]
Addressed in https://github.com/NVIDIA/gpu-monitoring-tools/commit/5c4f1effb51d19a6150b1551256e253eb6e899e9
