### ISSUE TITLE
/usr/local/bin/dcgm-exporter: line 167: kill: (13453) - No such process

### ISSUE THREAD

**Issue by aaktaev** [NVIDIA/gpu-monitoring-tools#57]
I've deployed dgcm-exporter on kubernetes on gpu node (https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/k8s/node-exporter/gpu-node-exporter-daemonset.yaml) .

@guptaNswati did fix, I've redeployed gpu exporter image, and now it fails with next error:
```
Starting NVIDIA host engine...
Collecting metrics at /run/prometheus/dcgm.prom every 1000ms...
Stopping NVIDIA host engine...
Unable to terminate host engine, it may not be running.
/usr/local/bin/dcgm-exporter: line 167: kill: (13453) - No such process
Done
```

**Comment by aaktaev** [comment]
@guptaNswati, is there any news about this issue?

**Comment by RenaudWasTaken** [comment]
This should be addressed in the new release :)
