### ISSUE TITLE
DCGM metrics not showing via curl xxxx:9100/metrics

### ISSUE THREAD

**Issue by c0nsaw** [NVIDIA/gpu-monitoring-tools#58]
DCGM metrics not showing via curl xxxx:9100/metrics, only node_*_ type metrics showing.

When I cat /run/prometheus/dcgm I do see what I want to collect.

Really no idea what I'm doing. Im new to this. Trying to scrape DCGM stats into prometheus on another server. Im working in an air gapped environment, so finding it hard to piece together, Im new enough to docker. I can see my GPUS so I think its running

```
#  docker exec nvidia-dcgm-exporter dcgmi discovery -i a -v | grep -c 'GPU ID:'
4
# nvidia-smi -L | wc -l
4
```

> dcgm_power_usage{gpu="3",uuid="GPU-807436aXXXYYYZZZZZZZ0547d1624eae"} 24.196

I think I need to output curl xxxx:9100/metrics to display all the dcgm_ metrics ?

Any help appreciated

**Comment by RenaudWasTaken** [comment]
This should be fixed with the new version :)
