### ISSUE TITLE
Getting helm chart to work on kubernetes 1.17

### ISSUE THREAD

**Issue by aruninnanje** [NVIDIA/gpu-monitoring-tools#59]
I am trying to get the helm charts to work on kubernetes 1.17. This doesn's work because there are changes to the template.
Can you please let me know how i can get access to the helm charts configuration files from repo?

**Comment by nvjmayo** [comment]
I am sorry this bug was lost for so long.

I believe this works now. If you still face this issue with the current version, please re-open and we will do better at responding to your problem.
