### ISSUE TITLE
pod gpu metric support for k8s-1.13

### ISSUE THREAD

**Issue by lazywhite** [NVIDIA/gpu-monitoring-tools#64]
I succeeded to get pod gpu metric using this daemonSet on k8s-v1.17.3

https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/k8s/node-exporter/pod-gpu-node-exporter-daemonset.yaml

Do you guys have a plan about making it work on k8s-v1.13 ?

**Comment by lazywhite** [comment]
sorry, I forget to open feature-gate , now it worked

**Comment by LRocc** [comment]
What happened to pod-gpu-node exporter? I can't seem to find the feature on the repo, was it unpublished?
