### ISSUE TITLE
Dashboard for DCGM metrics

### ISSUE THREAD

**Issue by muzammil360** [NVIDIA/gpu-monitoring-tools#67]
Hi. I am using [dcgm-exporter](https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/dcgm-exporter/dcgm-exporter) in conjunction with node-exporter for scraping gpu metrics. So far, I have been able to get the `dcgm_<metric>` metrics in prometheus. I was wondering if you guys have a grafana dashboard that can display the `dcgm` metrics. There seems to a number of them for kubernetes (with different metric names) but not for  `dcgm_<metric>` metrics.

**Comment by jaimehrubiks** [comment]
Same here! Can't find a good one

**Comment by RenaudWasTaken** [comment]
I added one here: https://grafana.com/grafana/dashboards/12219
Will update the README in a few minutes!

**Comment by RenaudWasTaken** [comment]
Actually I might create an NVIDIA account for this, give me a few minutes to do so

**Comment by RenaudWasTaken** [comment]
Done: https://grafana.com/grafana/dashboards/12239
