### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zan666** [NVIDIA/gpu-monitoring-tools#68]
![image](https://user-images.githubusercontent.com/43262330/79065496-4711f100-7ce3-11ea-88d1-4ca3a9c7cd41.png)

![image](https://user-images.githubusercontent.com/43262330/79065489-2c3f7c80-7ce3-11ea-8b40-7c777837e2b5.png)

**Comment by RenaudWasTaken** [comment]
Hello!

I cleaned up the exporter, feel free to pull the latest :)
