### ISSUE TITLE
Build instructions for nvml go bindings needed

### ISSUE THREAD

**Issue by karlmutch** [NVIDIA/gpu-monitoring-tools#7]
I am unable to build go software against the nvml go bindings due to the following error:
```
/tmp/go-build280384238/b001/exe/build: symbol lookup error: /tmp/go-build280384238/b001/exe/build: undefined symbol: nvmlDeviceGetCount_v2
```
Can anyone provide guidance on the explicit packages and requirements to compile this code.

I am installing the following packages cuda-nvml-dev-8-0 and nvidia-cuda-dev

One thing worth mentioning is that the build is occurring within a container and so I am looking to install the development libraries etc without having running hardware.

**Comment by guptaNswati** [comment]
You need at least cuda-9.0.
