### ISSUE TITLE
Pod GPU Metric Docs

### ISSUE THREAD

**Issue by JadCham** [NVIDIA/gpu-monitoring-tools#74]
Is it possible to export gpu metrics per pod? Is the pod gpu metric exporter still in this repo? I can't seem to find any information about it anymore. Is that a change with dcgm 2.0 ?  

The instructions link on master readme is broken where should it be pointing to? https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/#dcgm-exporter

**Comment by RenaudWasTaken** [comment]
Hello!

I've updated the front page with an example of the pod mapping when a GPU is used: https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/#quickstart-on-kubernetes

**Comment by LRocc** [comment]
> Hello!
> 
> I've updated the front page with an example of the pod mapping when a GPU is used: https://github.com/NVIDIA/gpu-monitoring-tools/tree/master/#quickstart-on-kubernetes

Hello, I can't seem to find the mentioned example? was the page edited again?
