### ISSUE TITLE
The DCGM make binary failed

### ISSUE THREAD

**Issue by eilinge** [NVIDIA/gpu-monitoring-tools#75]
env:
  datacenter-gpu-manager.x86_64            1.7.2-1
  go version go1.14.1 linux/amd64

flow:
[root@shpl009030064 gpu-monitoring-tools]# pwd
/root/zto-eilinge/gpu-monitor/gpu-monitoring-tools
[root@shpl009030064 gpu-monitoring-tools]# ls
bindings            docker  grafana   README.md
CONTRIBUTING.md     etc     LICENSE   RELEASE.md
dcgm-exporter.yaml  go.mod  Makefile  service-monitor.yaml
deployment          go.sum  pkg       vendor

failed logs:
[root@shpl009030064 gpu-monitoring-tools]# make binary
go build -o dcgm-exporter github.com/NVIDIA/gpu-monitoring-tools/pkg
# github.com/NVIDIA/gpu-monitoring-tools/bindings/go/dcgm
bindings/go/dcgm/api.go:20:13: undefined: mode
bindings/go/dcgm/api.go:65:33: undefined: Device
bindings/go/dcgm/api.go:70:35: undefined: DeviceStatus
bindings/go/dcgm/api.go:75:39: undefined: P2PLink
bindings/go/dcgm/api.go:81:24: undefined: GroupHandle

**Comment by eilinge** [comment]
export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
export GOROOT=/usr/local/go
#export GOBIN=$PATH:$GOROOT/bin
export GOBIN=$GOROOT/bin
export GOPROXY=https://goproxy.io
export GOARCH=amd64
export GOOS=linux
export CGO_ENABLED=0
export GO111MODULE=on
export GOTOOLS=$GOROOT/pkg/tool

i can run other go program in my env, but it failed when running make binary

**Comment by RenaudWasTaken** [comment]
Hello!

This seems like an issue with your setup, I would suggest you take a look at the Dockerfile: https://github.com/NVIDIA/gpu-monitoring-tools/blob/2.0.0-rc.10/docker/Dockerfile.ubuntu18.04

If you want you can also look into building the source in the dockerfile and copy the resulting binary to your machine by running `make image` and then `docker copy`
