### ISSUE TITLE
dcgm exporter produces 404 page not found

### ISSUE THREAD

**Issue by bbelgodere** [NVIDIA/gpu-monitoring-tools#78]
I've been using the python exporter that comes bundled with dcgm to monitor gpu cluster, but have run into issues when building the go package from source to run on bare metal.

Test environment is P100 on ubuntu 18.04.04 LTS
Nvidia driver 430.50
CUDA Version 10.1
dcgmi version 1.7.2
go version 1.14.3

using the default-counters.csv and dcp-metrics-included.csv

Build does not produce any errors, but running produces a ```404 page not found``` on port 9400

**Comment by bbelgodere** [comment]
dcgm_prometheus.py installed in /usr/local/dcgm/sdk_samples/scripts is running correctly on a separate port

**Comment by RenaudWasTaken** [comment]
Pretty sure you aren't querying the `/metrics` path :) 
Let me know if this fixes your issue :)

**Comment by bbelgodere** [comment]
@RenaudWasTaken I apologize, my mistake. I missed the metrics path in the example curl. May want to return something when you query the root path, similar to node-exporter. Is there a simple way to limit the exporter to listen only on localhost:9400 so I can wrap it up with TLS

**Comment by RenaudWasTaken** [comment]
I can look into that!

**Comment by RenaudWasTaken** [comment]
Latest commit has this feature request: https://github.com/NVIDIA/gpu-monitoring-tools/commit/57396c44e6f4a78e47e5af7b40860ec395790c78

**Comment by RenaudWasTaken** [comment]
Should now be part of rc.11

**Comment by RenaudWasTaken** [comment]
> Is there a simple way to limit the exporter to listen only on localhost:9400 so I can wrap it up with TLS

I'm not sure I understand the question  :)
There are a few examples out there on how to add SSL to a service and it really depends on your setup:
- https://kubernetes.io/blog/2015/07/strong-simple-ssl-for-kubernetes/
- https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion
- ...

I'd be happy to review a PR if you want to work on adding TLS support though :)
I'll be opening another issue for that!
