### ISSUE TITLE
DCGM REST API does not work

### ISSUE THREAD

**Issue by nikolayvoronchikhin** [NVIDIA/gpu-monitoring-tools#8]
../gpu-monitoring-tools/bindings/go/samples/dcgm/restApi > go build && ./restApi
2018/08/17 11:33:16 Running http server on localhost:8070
2018/08/17 11:33:31 error: localhost:8070/dcgm/device/info/id/GPUID: strconv.ParseUint: parsing "GPUID": invalid syntax
2018/08/17 11:33:46 error: localhost:8070/dcgm/device/info/id/GPUID/json: strconv.ParseUint: parsing "GPUID": invalid syntax
2018/08/17 11:33:55 error: localhost:8070/dcgm/process/info/pid/PID: strconv.ParseUint: parsing "PID": invalid syntax
2018/08/17 11:34:05 error: localhost:8070/dcgm/health/id/GPUID: strconv.ParseUint: parsing "GPUID": invalid syntax

**Comment by guptaNswati** [comment]
Did you replace the GPUID with the actual GPUID i.e if you are trying to get information for GPU 0, do `localhost:8070/dcgm/device/info/id/0`

**Comment by nikolayvoronchikhin** [comment]
That is perfect, it works! Thank you.
