### ISSUE TITLE
Fan status and card count requirements

### ISSUE THREAD

**Issue by guleng** [NVIDIA/gpu-monitoring-tools#84]
I have a need to check the GPU fan speed or check its fan health status, because we have hundreds of fans that are damaged and unknown. In addition, we need to check the metrics of how many GPU cards a machine has to judge whether the card has dropped And whether the card has Huang card dead state monitoring

**Comment by likueimo** [comment]
According [DCGM API](https://docs.nvidia.com/datacenter/dcgm/latest/dcgm-api/group__dcgmFieldIdentifiers.html), I guess that you can use `DCGM_FI_DEV_FAN_SPEED`.  
Add to [default-counters.csv](https://github.com/NVIDIA/gpu-monitoring-tools/blob/2.0.0-rc.11/etc/dcgm-exporter/default-counters.csv).

**Comment by RenaudWasTaken** [comment]
Thanks for helping @likueimo !
That's pretty much what you need to do :)
More details here: https://github.com/NVIDIA/gpu-monitoring-tools#changing-the-metrics
