### ISSUE TITLE
Option to pass hostname/ip along with port

### ISSUE THREAD

**Issue by bbelgodere** [NVIDIA/gpu-monitoring-tools#85]
Currently,  dcgm-exporter accepts a port value (int) that is then used to start the webserver, which binds to 0.0.0.0, i.e. "listen on every available network interface". node-exporter can accept hostname and port via the "--web.listen-address=":9100" option allowing a users to run the webserver on localhost/127.0.0.1 only. A reverse proxy can then be used to secure the endpoint. 

Working with @colm-anseo, created a rough solution by adding a new flag in main.go

```
// optional -a flag which allows host & port as a string
&cli.StringFlag{
        Name:    CLIAddress,
        Aliases: []string{"a"},
        Value:   "",
        Usage:   "Address",
        EnvVars: []string{"DCGM_EXPORTER_LISTEN_ADDR"},
},
```
Then 

added the following to server.go

```
if c.Address == "" {
        c.Address = fmt.Sprintf(":%d", c.Port)
}
```

```
serverv1 := &MetricsServer{
              server: http.Server{
                      Addr:         c.Address,
```
Not sure if it made sense to just expand/change port option or add a separate option.

Compiled against x86 and ppc64le on RHEL 7.7 without issue.

**Comment by bbelgodere** [comment]
@colm-anseo

**Comment by RenaudWasTaken** [comment]
Hello!

I'd be happy to accept a pull request for this! We're still in rc so "breaking" API/CLI changes are ok!

**Comment by colm-anseo** [comment]
**address** flag does make **port** (flag/ENV-VAR/config) redundant - but I left it in for backward compatibility. But from above comment it seems like **port** can be removed.

**Comment by RenaudWasTaken** [comment]
Closing this one, thanks for contributing!
