### ISSUE TITLE
How to Load NVML library in docker without nvidia-docker runtime

### ISSUE THREAD

**Issue by pytimer** [NVIDIA/gpu-monitoring-tools#9]
Hi, all

I write a tool to get nvidia gpu metrics, i already install nvidia device on my host and works well, but this host not install nvidia-docker runtime. 

Now i want to run my application in docker without nvidia-docker runtime, i want to know which libs should be mount in docker.

Thanks.

**Comment by guptaNswati** [comment]
The easiest is to use nvidia-docker. But if you don't want to use nvidia runtime, look at [libnvidia](https://github.com/NVIDIA/libnvidia-container) or [driver container](https://github.com/NVIDIA/nvidia-docker/wiki/Driver-containers-(EXPERIMENTAL)).

**Comment by pytimer** [comment]
OK, Thanks.

I will try it.
