### ISSUE TITLE
Failed to initialize NVML

### ISSUE THREAD

**Issue by guleng** [NVIDIA/gpu-monitoring-tools#90]
I deployed it in k8s with wrong package

Error: Failed to initialize NVML

But I can execute it directly in docker. Does this depend on k8s? I'm k8s: 1.16.8
docker：19.03.11   
![image](https://user-images.githubusercontent.com/40238640/85383852-149e3300-b573-11ea-8af7-8b52ec617e37.png)

**Comment by tanrobotix** [comment]
@guleng Hello, how did you fix this issue
